function y = cheby_bpm(x)
%cheby_bpm Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.10 and DSP System Toolbox 9.12.
% Generated on: 14-Apr-2021 19:44:08

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    %
    % N      = 10;   % Order
    % Fpass1 = 0.7;  % First Passband Frequency
    % Fpass2 = 10;   % Second Passband Frequency
    % Apass  = 1;    % Passband Ripple (dB)
    % Fs     = 60;   % Sampling Frequency
    %
    % h = fdesign.bandpass('n,fp1,fp2,ap', N, Fpass1, Fpass2, Apass, Fs);
    %
    % Hd = design(h, 'cheby1', ...
    %     'SystemObject', true);
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 0 -1 1 -0.944372970772985 0.872003134685967; 1 0 -1 ...
        1 -1.98299487497534 0.988398931441531; 1 0 -1 1 -1.21827347624622 ...
        0.676648411709279; 1 0 -1 1 -1.93119047394714 0.942154328933154; 1 0 -1 ...
        1 -1.66228117537684 0.734185992902418], ...
        'ScaleValues', [0.449413733078882; 0.449413733078882; ...
        0.296566951142936; 0.296566951142936; 0.132907003548791; 1]);
end

s = double(x);
y = step(Hd,s);

