function y = cheby_rr(x)
%cheby_rr Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.10 and DSP System Toolbox 9.12.
% Generated on: 14-Apr-2021 19:44:26

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    %
    % N      = 10;   % Order
    % Fpass1 = 0.1;  % First Passband Frequency
    % Fpass2 = 0.6;  % Second Passband Frequency
    % Apass  = 1;    % Passband Ripple (dB)
    % Fs     = 60;   % Sampling Frequency
    %
    % h = fdesign.bandpass('n,fp1,fp2,ap', N, Fpass1, Fpass2, Apass, Fs);
    %
    % Hd = design(h, 'cheby1', ...
    %     'SystemObject', true);
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 0 -1 1 -1.98813253288125 0.992019452218469; 1 0 -1 1 ...
        -1.99853872877092 0.998649554215318; 1 0 -1 1 -1.97915424046992 ...
        0.9813220148784; 1 0 -1 1 -1.99414785957648 0.994345162224273; 1 0 -1 1 ...
        -1.98429963123845 0.984952767941833], ...
        'ScaleValues', [0.0259629554973463; 0.0259629554973463; ...
        0.0170504888180193; 0.0170504888180193; 0.00752361602908334; 1]);
end

s = double(x);
y = step(Hd,s);

